language: csharp
solution: bCC.sln

install:
  - nuget restore bCC.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release bCC.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./bCC-Test/bin/Release/bCC_Test.exe

